### ISSUE TITLE
Assign submissions to user using GitHub pull request hoooks

### ISSUE THREAD

**Issue by L3K0V** [L3K0V/lifebelt#19]

**Comment by L3K0V** [comment]
Use Django signals to publish receiving hook event

**Comment by L3K0V** [comment]
So, in 693e8e4820171478372b331416e1f0f794629eea we have initial submission receive hook handling, but some validation checks must be perfomed:

- [ ] Check if pull_request repo URL is target one.
- [ ] DB model validation unique pull_request numbers combine with author for given course
- [ ] Handle open-reopen request, but this must be discussed. Is there need to handle reopen of pull_request? @migglu and @bankin

**Comment by bankin** [comment]
If we have track of the relation github-profile -> student we can just
check that and our workflow will be to decline wrong/bad pull requests and
they will create new ones. I think we can go without this for now.

On Sun, Oct 4, 2015 at 11:24 PM, Asen Lekov <notifications@github.com>
wrote:

> So, in 693e8e4
> <https://github.com/L3K0V/lifebelt/commit/693e8e4820171478372b331416e1f0f794629eea>
> we have initial submission receive hook handling, but some validation
> checks must be perfomed:
>
>    - Check if pull_request repo URL is target one.
>    - DB model validation unique pull_request numbers combine with author
>    for given course
>    - Handle open-reopen request, but this must be discussed. Is there
>    need to handle reopen of pull_request? @migglu
>    <https://github.com/migglu> and @bankin <https://github.com/bankin>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/L3K0V/lifebelt/issues/19#issuecomment-145384778>.
>



-- 
Best regards,
*Nikolay Bankin*
Developer
*email: niky.bankin@gmail.com <niky.bankin@gmail.com>*
